//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\moroc\Desktop\UNIVERSIDAD\Construccion\musa\MusaLang\MusaLanguage\musa.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="musaParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface ImusaVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="musaParser.musa"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMusa([NotNull] musaParser.MusaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="musaParser.comando"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComando([NotNull] musaParser.ComandoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="musaParser.loopFor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoopFor([NotNull] musaParser.LoopForContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="musaParser.loopWhile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoopWhile([NotNull] musaParser.LoopWhileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="musaParser.condicion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondicion([NotNull] musaParser.CondicionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="musaParser.impresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImpresion([NotNull] musaParser.ImpresionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>int</c>
	/// labeled alternative in <see cref="musaParser.asignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInt([NotNull] musaParser.IntContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>string</c>
	/// labeled alternative in <see cref="musaParser.asignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] musaParser.StringContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>sumORes</c>
	/// labeled alternative in <see cref="musaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSumORes([NotNull] musaParser.SumOResContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>terminoSolo</c>
	/// labeled alternative in <see cref="musaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerminoSolo([NotNull] musaParser.TerminoSoloContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>mulODiv</c>
	/// labeled alternative in <see cref="musaParser.termino"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMulODiv([NotNull] musaParser.MulODivContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>factorSolo</c>
	/// labeled alternative in <see cref="musaParser.termino"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactorSolo([NotNull] musaParser.FactorSoloContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numero</c>
	/// labeled alternative in <see cref="musaParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumero([NotNull] musaParser.NumeroContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>identificador</c>
	/// labeled alternative in <see cref="musaParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentificador([NotNull] musaParser.IdentificadorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>subexpresion</c>
	/// labeled alternative in <see cref="musaParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubexpresion([NotNull] musaParser.SubexpresionContext context);
}
