//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\moroc\Desktop\UNIVERSIDAD\Construccion\musa\MusaLang\MusaLanguage\musa.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class musaLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		FOR=1, WHILE=2, IMP=3, BOOLEAN=4, IF=5, THEN=6, ELSE=7, NUM=8, PALABRA=9, 
		ID=10, WORD=11, COMA=12, QUOTE=13, SUM=14, DIF=15, DIV=16, MULT=17, ASSIGN=18, 
		INSEP=19, SBR=20, EBR=21, SPAR=22, EPAR=23, SEP=24, OP=25, EQUAL=26, WS=27, 
		SK2=28, SK3=29;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"FOR", "WHILE", "IMP", "BOOLEAN", "IF", "THEN", "ELSE", "NUM", "PALABRA", 
		"ID", "WORD", "COMA", "QUOTE", "SUM", "DIF", "DIV", "MULT", "ASSIGN", 
		"INSEP", "SBR", "EBR", "SPAR", "EPAR", "SEP", "OP", "EQUAL", "WS", "SK2", 
		"SK3"
	};


	public musaLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public musaLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'for'", "'while'", "'monta'", null, "'if'", "'then'", "'else'", 
		null, null, null, null, "','", "'\"'", "'+'", "'-'", "'/'", "'*'", "'<-'", 
		"';'", "'['", "']'", "'('", "')'", "' '", null, "'='", "'\n'", "'\r'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "FOR", "WHILE", "IMP", "BOOLEAN", "IF", "THEN", "ELSE", "NUM", "PALABRA", 
		"ID", "WORD", "COMA", "QUOTE", "SUM", "DIF", "DIV", "MULT", "ASSIGN", 
		"INSEP", "SBR", "EBR", "SPAR", "EPAR", "SEP", "OP", "EQUAL", "WS", "SK2", 
		"SK3"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "musa.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static musaLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x1F', '\xC3', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x5', '\x5', '`', '\n', '\x5', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\t', '\x6', '\t', 'p', '\n', '\t', '\r', '\t', '\xE', '\t', 
		'q', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x5', '\n', 
		'x', '\n', '\n', '\x3', '\v', '\x6', '\v', '{', '\n', '\v', '\r', '\v', 
		'\xE', '\v', '|', '\x3', '\v', '\a', '\v', '\x80', '\n', '\v', '\f', '\v', 
		'\xE', '\v', '\x83', '\v', '\v', '\x3', '\f', '\x6', '\f', '\x86', '\n', 
		'\f', '\r', '\f', '\xE', '\f', '\x87', '\x3', '\r', '\x3', '\r', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x15', '\x3', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x3', 
		'\x17', '\x3', '\x18', '\x3', '\x18', '\x3', '\x19', '\x3', '\x19', '\x3', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x5', '\x1A', '\xAE', 
		'\n', '\x1A', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1C', '\x3', '\x1C', 
		'\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', 
		'\x3', '\x1D', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', 
		'\x6', '\x1E', '\xBE', '\n', '\x1E', '\r', '\x1E', '\xE', '\x1E', '\xBF', 
		'\x3', '\x1E', '\x3', '\x1E', '\x2', '\x2', '\x1F', '\x3', '\x3', '\x5', 
		'\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', 
		'\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', 
		'\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', '\x13', 
		'%', '\x14', '\'', '\x15', ')', '\x16', '+', '\x17', '-', '\x18', '/', 
		'\x19', '\x31', '\x1A', '\x33', '\x1B', '\x35', '\x1C', '\x37', '\x1D', 
		'\x39', '\x1E', ';', '\x1F', '\x3', '\x2', '\x5', '\x3', '\x2', '\x32', 
		';', '\x4', '\x2', '\x43', '\\', '\x63', '|', '\x4', '\x2', '>', '>', 
		'@', '@', '\x2', '\xCF', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', 
		'\x2', '\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x2', '/', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x33', '\x3', '\x2', '\x2', '\x2', '\x2', '\x35', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x37', '\x3', '\x2', '\x2', '\x2', '\x2', '\x39', 
		'\x3', '\x2', '\x2', '\x2', '\x2', ';', '\x3', '\x2', '\x2', '\x2', '\x3', 
		'=', '\x3', '\x2', '\x2', '\x2', '\x5', '\x41', '\x3', '\x2', '\x2', '\x2', 
		'\a', 'G', '\x3', '\x2', '\x2', '\x2', '\t', '_', '\x3', '\x2', '\x2', 
		'\x2', '\v', '\x61', '\x3', '\x2', '\x2', '\x2', '\r', '\x64', '\x3', 
		'\x2', '\x2', '\x2', '\xF', 'i', '\x3', '\x2', '\x2', '\x2', '\x11', 'o', 
		'\x3', '\x2', '\x2', '\x2', '\x13', 'w', '\x3', '\x2', '\x2', '\x2', '\x15', 
		'z', '\x3', '\x2', '\x2', '\x2', '\x17', '\x85', '\x3', '\x2', '\x2', 
		'\x2', '\x19', '\x89', '\x3', '\x2', '\x2', '\x2', '\x1B', '\x8B', '\x3', 
		'\x2', '\x2', '\x2', '\x1D', '\x8D', '\x3', '\x2', '\x2', '\x2', '\x1F', 
		'\x8F', '\x3', '\x2', '\x2', '\x2', '!', '\x91', '\x3', '\x2', '\x2', 
		'\x2', '#', '\x93', '\x3', '\x2', '\x2', '\x2', '%', '\x95', '\x3', '\x2', 
		'\x2', '\x2', '\'', '\x98', '\x3', '\x2', '\x2', '\x2', ')', '\x9A', '\x3', 
		'\x2', '\x2', '\x2', '+', '\x9C', '\x3', '\x2', '\x2', '\x2', '-', '\x9E', 
		'\x3', '\x2', '\x2', '\x2', '/', '\xA0', '\x3', '\x2', '\x2', '\x2', '\x31', 
		'\xA2', '\x3', '\x2', '\x2', '\x2', '\x33', '\xAD', '\x3', '\x2', '\x2', 
		'\x2', '\x35', '\xAF', '\x3', '\x2', '\x2', '\x2', '\x37', '\xB1', '\x3', 
		'\x2', '\x2', '\x2', '\x39', '\xB5', '\x3', '\x2', '\x2', '\x2', ';', 
		'\xBD', '\x3', '\x2', '\x2', '\x2', '=', '>', '\a', 'h', '\x2', '\x2', 
		'>', '?', '\a', 'q', '\x2', '\x2', '?', '@', '\a', 't', '\x2', '\x2', 
		'@', '\x4', '\x3', '\x2', '\x2', '\x2', '\x41', '\x42', '\a', 'y', '\x2', 
		'\x2', '\x42', '\x43', '\a', 'j', '\x2', '\x2', '\x43', '\x44', '\a', 
		'k', '\x2', '\x2', '\x44', '\x45', '\a', 'n', '\x2', '\x2', '\x45', '\x46', 
		'\a', 'g', '\x2', '\x2', '\x46', '\x6', '\x3', '\x2', '\x2', '\x2', 'G', 
		'H', '\a', 'o', '\x2', '\x2', 'H', 'I', '\a', 'q', '\x2', '\x2', 'I', 
		'J', '\a', 'p', '\x2', '\x2', 'J', 'K', '\a', 'v', '\x2', '\x2', 'K', 
		'L', '\a', '\x63', '\x2', '\x2', 'L', '\b', '\x3', '\x2', '\x2', '\x2', 
		'M', 'N', '\a', 'V', '\x2', '\x2', 'N', 'O', '\a', 'T', '\x2', '\x2', 
		'O', 'P', '\a', 'W', '\x2', '\x2', 'P', '`', '\a', 'G', '\x2', '\x2', 
		'Q', 'R', '\a', 'H', '\x2', '\x2', 'R', 'S', '\a', '\x43', '\x2', '\x2', 
		'S', 'T', '\a', 'N', '\x2', '\x2', 'T', 'U', '\a', 'U', '\x2', '\x2', 
		'U', '`', '\a', 'G', '\x2', '\x2', 'V', 'W', '\a', 'v', '\x2', '\x2', 
		'W', 'X', '\a', 't', '\x2', '\x2', 'X', 'Y', '\a', 'w', '\x2', '\x2', 
		'Y', '`', '\a', 'g', '\x2', '\x2', 'Z', '[', '\a', 'h', '\x2', '\x2', 
		'[', '\\', '\a', '\x63', '\x2', '\x2', '\\', ']', '\a', 'n', '\x2', '\x2', 
		']', '^', '\a', 'u', '\x2', '\x2', '^', '`', '\a', 'g', '\x2', '\x2', 
		'_', 'M', '\x3', '\x2', '\x2', '\x2', '_', 'Q', '\x3', '\x2', '\x2', '\x2', 
		'_', 'V', '\x3', '\x2', '\x2', '\x2', '_', 'Z', '\x3', '\x2', '\x2', '\x2', 
		'`', '\n', '\x3', '\x2', '\x2', '\x2', '\x61', '\x62', '\a', 'k', '\x2', 
		'\x2', '\x62', '\x63', '\a', 'h', '\x2', '\x2', '\x63', '\f', '\x3', '\x2', 
		'\x2', '\x2', '\x64', '\x65', '\a', 'v', '\x2', '\x2', '\x65', '\x66', 
		'\a', 'j', '\x2', '\x2', '\x66', 'g', '\a', 'g', '\x2', '\x2', 'g', 'h', 
		'\a', 'p', '\x2', '\x2', 'h', '\xE', '\x3', '\x2', '\x2', '\x2', 'i', 
		'j', '\a', 'g', '\x2', '\x2', 'j', 'k', '\a', 'n', '\x2', '\x2', 'k', 
		'l', '\a', 'u', '\x2', '\x2', 'l', 'm', '\a', 'g', '\x2', '\x2', 'm', 
		'\x10', '\x3', '\x2', '\x2', '\x2', 'n', 'p', '\t', '\x2', '\x2', '\x2', 
		'o', 'n', '\x3', '\x2', '\x2', '\x2', 'p', 'q', '\x3', '\x2', '\x2', '\x2', 
		'q', 'o', '\x3', '\x2', '\x2', '\x2', 'q', 'r', '\x3', '\x2', '\x2', '\x2', 
		'r', '\x12', '\x3', '\x2', '\x2', '\x2', 's', 'x', '\x5', '\x11', '\t', 
		'\x2', 't', 'u', '\x5', '\x11', '\t', '\x2', 'u', 'v', '\x5', '\x17', 
		'\f', '\x2', 'v', 'x', '\x3', '\x2', '\x2', '\x2', 'w', 's', '\x3', '\x2', 
		'\x2', '\x2', 'w', 't', '\x3', '\x2', '\x2', '\x2', 'x', '\x14', '\x3', 
		'\x2', '\x2', '\x2', 'y', '{', '\t', '\x3', '\x2', '\x2', 'z', 'y', '\x3', 
		'\x2', '\x2', '\x2', '{', '|', '\x3', '\x2', '\x2', '\x2', '|', 'z', '\x3', 
		'\x2', '\x2', '\x2', '|', '}', '\x3', '\x2', '\x2', '\x2', '}', '\x81', 
		'\x3', '\x2', '\x2', '\x2', '~', '\x80', '\t', '\x2', '\x2', '\x2', '\x7F', 
		'~', '\x3', '\x2', '\x2', '\x2', '\x80', '\x83', '\x3', '\x2', '\x2', 
		'\x2', '\x81', '\x7F', '\x3', '\x2', '\x2', '\x2', '\x81', '\x82', '\x3', 
		'\x2', '\x2', '\x2', '\x82', '\x16', '\x3', '\x2', '\x2', '\x2', '\x83', 
		'\x81', '\x3', '\x2', '\x2', '\x2', '\x84', '\x86', '\t', '\x3', '\x2', 
		'\x2', '\x85', '\x84', '\x3', '\x2', '\x2', '\x2', '\x86', '\x87', '\x3', 
		'\x2', '\x2', '\x2', '\x87', '\x85', '\x3', '\x2', '\x2', '\x2', '\x87', 
		'\x88', '\x3', '\x2', '\x2', '\x2', '\x88', '\x18', '\x3', '\x2', '\x2', 
		'\x2', '\x89', '\x8A', '\a', '.', '\x2', '\x2', '\x8A', '\x1A', '\x3', 
		'\x2', '\x2', '\x2', '\x8B', '\x8C', '\a', '$', '\x2', '\x2', '\x8C', 
		'\x1C', '\x3', '\x2', '\x2', '\x2', '\x8D', '\x8E', '\a', '-', '\x2', 
		'\x2', '\x8E', '\x1E', '\x3', '\x2', '\x2', '\x2', '\x8F', '\x90', '\a', 
		'/', '\x2', '\x2', '\x90', ' ', '\x3', '\x2', '\x2', '\x2', '\x91', '\x92', 
		'\a', '\x31', '\x2', '\x2', '\x92', '\"', '\x3', '\x2', '\x2', '\x2', 
		'\x93', '\x94', '\a', ',', '\x2', '\x2', '\x94', '$', '\x3', '\x2', '\x2', 
		'\x2', '\x95', '\x96', '\a', '>', '\x2', '\x2', '\x96', '\x97', '\a', 
		'/', '\x2', '\x2', '\x97', '&', '\x3', '\x2', '\x2', '\x2', '\x98', '\x99', 
		'\a', '=', '\x2', '\x2', '\x99', '(', '\x3', '\x2', '\x2', '\x2', '\x9A', 
		'\x9B', '\a', ']', '\x2', '\x2', '\x9B', '*', '\x3', '\x2', '\x2', '\x2', 
		'\x9C', '\x9D', '\a', '_', '\x2', '\x2', '\x9D', ',', '\x3', '\x2', '\x2', 
		'\x2', '\x9E', '\x9F', '\a', '*', '\x2', '\x2', '\x9F', '.', '\x3', '\x2', 
		'\x2', '\x2', '\xA0', '\xA1', '\a', '+', '\x2', '\x2', '\xA1', '\x30', 
		'\x3', '\x2', '\x2', '\x2', '\xA2', '\xA3', '\a', '\"', '\x2', '\x2', 
		'\xA3', '\x32', '\x3', '\x2', '\x2', '\x2', '\xA4', '\xA5', '\a', '?', 
		'\x2', '\x2', '\xA5', '\xAE', '\a', '?', '\x2', '\x2', '\xA6', '\xAE', 
		'\t', '\x4', '\x2', '\x2', '\xA7', '\xA8', '\a', '@', '\x2', '\x2', '\xA8', 
		'\xAE', '\a', '?', '\x2', '\x2', '\xA9', '\xAA', '\a', '>', '\x2', '\x2', 
		'\xAA', '\xAE', '\a', '?', '\x2', '\x2', '\xAB', '\xAC', '\a', '>', '\x2', 
		'\x2', '\xAC', '\xAE', '\a', '@', '\x2', '\x2', '\xAD', '\xA4', '\x3', 
		'\x2', '\x2', '\x2', '\xAD', '\xA6', '\x3', '\x2', '\x2', '\x2', '\xAD', 
		'\xA7', '\x3', '\x2', '\x2', '\x2', '\xAD', '\xA9', '\x3', '\x2', '\x2', 
		'\x2', '\xAD', '\xAB', '\x3', '\x2', '\x2', '\x2', '\xAE', '\x34', '\x3', 
		'\x2', '\x2', '\x2', '\xAF', '\xB0', '\a', '?', '\x2', '\x2', '\xB0', 
		'\x36', '\x3', '\x2', '\x2', '\x2', '\xB1', '\xB2', '\a', '\f', '\x2', 
		'\x2', '\xB2', '\xB3', '\x3', '\x2', '\x2', '\x2', '\xB3', '\xB4', '\b', 
		'\x1C', '\x2', '\x2', '\xB4', '\x38', '\x3', '\x2', '\x2', '\x2', '\xB5', 
		'\xB6', '\a', '\xF', '\x2', '\x2', '\xB6', '\xB7', '\x3', '\x2', '\x2', 
		'\x2', '\xB7', '\xB8', '\b', '\x1D', '\x2', '\x2', '\xB8', ':', '\x3', 
		'\x2', '\x2', '\x2', '\xB9', '\xBA', '\a', '\"', '\x2', '\x2', '\xBA', 
		'\xBB', '\a', '\"', '\x2', '\x2', '\xBB', '\xBC', '\a', '\"', '\x2', '\x2', 
		'\xBC', '\xBE', '\a', '\"', '\x2', '\x2', '\xBD', '\xB9', '\x3', '\x2', 
		'\x2', '\x2', '\xBE', '\xBF', '\x3', '\x2', '\x2', '\x2', '\xBF', '\xBD', 
		'\x3', '\x2', '\x2', '\x2', '\xBF', '\xC0', '\x3', '\x2', '\x2', '\x2', 
		'\xC0', '\xC1', '\x3', '\x2', '\x2', '\x2', '\xC1', '\xC2', '\b', '\x1E', 
		'\x2', '\x2', '\xC2', '<', '\x3', '\x2', '\x2', '\x2', '\v', '\x2', '_', 
		'q', 'w', '|', '\x81', '\x87', '\xAD', '\xBF', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
